name: Run Specific Playwright Test

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.19

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Get commit message
        id: get_msg
        run: |
          echo "msg=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Run specific Playwright test
        run: |
          COMMIT_MSG="${{ env.msg }}"
          echo "Commit message: $COMMIT_MSG"

          # Extract the test name keyword from commit message
          if [[ "$COMMIT_MSG" =~ run:([a-zA-Z0-9_-]+) ]]; then
            TEST_NAME="${BASH_REMATCH[1]}"
            echo "Running test matching: $TEST_NAME"
            npx playwright test --headless --grep "$TEST_NAME"
          else
            echo "No test keyword found. Running all tests."
            npx playwright test --headless
          fi
